services:
  app:
    image: info21_app
    build: /App/.
    volumes:
      - db-data:/var/lib/postgresql/data

  database:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./Database/db.sql:/docker-entrypoint-initdb.d/db.sql
      - db-data:/var/lib/postgresql/data

  web:
    image: info21_nginx
    build: /Web/.
    ports:
      - 7777:8080

volumes:
  db-data:
    name: "info21_data"